### ISSUE TITLE
can't register 

### ISSUE THREAD

**Issue by iokane** [PredixDev/predix-jpa-cf#1]
I'm from China。
I can't register on the website（predix.io）。

**Comment by Ernesto-Valdes** [comment]
<img width="1280" alt="predix-registration-china" src="https://user-images.githubusercontent.com/4762763/27346355-ec58daf0-55ba-11e7-97fc-7bf5b8003c11.png">

**Comment by gstroup** [comment]
This issue is not related to this github repo.  Please open a ticket with Predix support. 
https://www.predix.io/support/
Scroll down, and on the right is a link for "Sign up/Sign in help"
